steps:
  - label: "Test"
    command: npm ci && npm test
    parallelism: 2
    agents:
      queue: default
  - label: "Long running job"
    command: sleep 300
    parallelism: 2
    agents:
      queue: default
